In [1]:
from dataclasses import dataclass, field
from typing import Dict, Any
import pandas as pd


@dataclass
class TimeSeriesBundle:
    data: pd.DataFrame
    meta: Dict[str, Any] = field(default_factory=dict)

    def __post_init__(self):
        """
        Initialize metadata after object creation.
        """
        if not isinstance(self.data.index, pd.DatetimeIndex):
            raise ValueError("DataFrame index must be a DatetimeIndex.")

        # Ensure sorted index
        self.data = self.data.sort_index()

        # Initialize metadata
        self.meta = {
            "frequency": pd.infer_freq(self.data.index),
            "index_start": self.data.index.min(),
            "index_end": self.data.index.max(),
            "n_rows": len(self.data),
            "n_columns": self.data.shape[1],
            "columns": self._build_column_metadata()
        }

    def _build_column_metadata(self) -> Dict[str, Dict[str, Any]]:
        """
        Build per-column metadata.
        """
        col_meta = {}

        for col in self.data.columns:
            series = self.data[col]
            col_meta[col] = {
                "first_valid": series.first_valid_index(),
                "last_valid": series.last_valid_index(),
                "n_valid": series.notna().sum(),
                "n_missing": series.isna().sum(),
            }

        return col_meta

    def add_series(self, name: str, series: pd.Series, align: bool = True):
        """
        Add a new time series to the bundle.

        Parameters
        ----------
        name : str
            Column name to assign.
        series : pd.Series
            Series with DatetimeIndex.
        align : bool
            If True, align to existing index.
        """
        if not isinstance(series.index, pd.DatetimeIndex):
            raise ValueError("Series index must be a DatetimeIndex.")

        if align:
            series = series.reindex(self.data.index)

        self.data[name] = series

        # Update metadata
        self.meta["columns"][name] = {
            "first_valid": series.first_valid_index(),
            "last_valid": series.last_valid_index(),
            "n_valid": series.notna().sum(),
            "n_missing": series.isna().sum(),
        }

        self.meta["n_columns"] = self.data.shape[1]

    def refresh_metadata(self):
        """
        Recalculate all metadata (useful after bulk edits).
        """
        self.meta["frequency"] = pd.infer_freq(self.data.index)
        self.meta["index_start"] = self.data.index.min()
        self.meta["index_end"] = self.data.index.max()
        self.meta["n_rows"] = len(self.data)
        self.meta["n_columns"] = self.data.shape[1]
        self.meta["columns"] = self._build_column_metadata()

In [2]:
import pandas as pd
from pathlib import Path
from typing import Union, List, Optional, Literal

AggMethod = Literal["mean", "sum", "median", "min", "max", "first", "last"]


def _floor_to_month_start(idx: pd.DatetimeIndex) -> pd.DatetimeIndex:
    # Works for any timestamp within a month (and preserves timezone if present)
    return idx - pd.to_timedelta(idx.day - 1, unit="D")


def _calendar_floor_index(idx: pd.DatetimeIndex, freq: str) -> pd.DatetimeIndex:
    """
    Calendar 'floor' for non-fixed freqs. Uses safe datetime math for MS,
    and Period conversion for others.
    """
    f = freq.upper()

    if f == "MS":
        return _floor_to_month_start(idx)

    # For other calendar freqs, Period-based conversion is usually fine.
    mapping = {
        "M":  ("M", "M"),    # month end
        "QS": ("Q", "QS"),   # quarter start
        "Q":  ("Q", "Q"),    # quarter end
        "AS": ("Y", "YS"),   # year start (legacy alias)
        "YS": ("Y", "YS"),   # year start
        "A":  ("Y", "Y"),    # year end (legacy alias)
        "Y":  ("Y", "Y"),    # year end
    }

    if f not in mapping:
        raise ValueError(
            f"Non-fixed floor frequency '{freq}' not recognized. "
            f"Use one of: {sorted(['MS', *mapping.keys()])}, or a fixed freq like 'D', 'H', '15min'."
        )

    period_freq, ts_freq = mapping[f]
    return idx.to_period(period_freq).to_timestamp(ts_freq)


def load_timeseries_csv(
    path: Union[str, Path],
    time_col: str,
    value_cols: Union[str, List[str]],
    floor_freq: Optional[str] = None,
    dropna_time: bool = True,
    floor_agg: Optional[AggMethod] = None,          # required if flooring creates duplicates
    resample_freq: Optional[str] = None,
    resample_how: Optional[AggMethod] = None,       # required if resample_freq is set
) -> pd.DataFrame:
    """
    Load and clean a CSV time series file.

    - Converts `time_col` to datetime and sets as DatetimeIndex
    - Optionally floors timestamps (fixed freqs via .floor; calendar freqs via helpers)
    - Optionally resamples to a target frequency

    Safety rule:
    - If flooring creates duplicate timestamps, you MUST specify how to aggregate
      (either floor_agg, or resample_freq + resample_how).
    """

    path = Path(path).expanduser()
    df = pd.read_csv(path)

    df[time_col] = pd.to_datetime(df[time_col], errors="coerce")
    if dropna_time:
        df = df.dropna(subset=[time_col])

    df = df.set_index(time_col).sort_index()

    if isinstance(value_cols, str):
        value_cols = [value_cols]

    df = df[value_cols].apply(pd.to_numeric, errors="coerce")

    # ---------- Flooring (labeling / alignment) ----------
    if floor_freq is not None:
        idx = df.index

        # Fixed freqs use .floor(); calendar freqs use helper
        try:
            floored = idx.floor(floor_freq)
        except ValueError as e:
            # includes "non-fixed frequency" and some "period frequency" errors
            floored = _calendar_floor_index(idx, floor_freq)

        # If flooring collapses multiple rows into same timestamp, require explicit aggregation choice
        if floored.has_duplicates:
            if floor_agg is None and (resample_freq is None or resample_how is None):
                raise ValueError(
                    f"Flooring to '{floor_freq}' would create duplicate timestamps (multiple observations per bin). "
                    f"To avoid silent aggregation, you must either:\n"
                    f"  1) specify floor_agg='mean'|'sum'|'median'|'min'|'max'|'first'|'last', OR\n"
                    f"  2) specify resample_freq=... AND resample_how=... to aggregate via resampling.\n"
                    f"Example (discharge): resample_freq='{floor_freq}', resample_how='mean'"
                )

            df = df.copy()
            df.index = floored

            if floor_agg is not None:
                gb = df.groupby(df.index)
                df = getattr(gb, floor_agg)()
        else:
            df = df.copy()
            df.index = floored

    # ---------- Resampling (true binning/aggregation) ----------
    if resample_freq is not None:
        if resample_how is None:
            raise ValueError(
                "You set resample_freq but did not set resample_how. "
                "Specify resample_how='mean'|'sum'|'median'|'min'|'max'|'first'|'last'."
            )
        rs = df.resample(resample_freq)
        df = getattr(rs, resample_how)()

    return df

In [3]:
testdf = load_timeseries_csv('~/signal-extraction/vae_input_data/AR_cfs.csv','time','cfs','MS')

In [4]:
testdf

                cfs
time
1940-01-01  24300.0
1940-02-01  57500.0
1940-03-01  69600.0
1940-04-01  29800.0
1940-05-01  11300.0
...             ...
2025-02-01   7730.0
2025-03-01   6400.0
2025-04-01   7480.0
2025-05-01   4090.0
2025-06-01   2500.0

[1026 rows x 1 columns]

In [5]:
print(testdf.head())
print(type(testdf.index))
print(testdf.index.freq)   # may be None; that's okay

                cfs
time
1940-01-01  24300.0
1940-02-01  57500.0
1940-03-01  69600.0
1940-04-01  29800.0
1940-05-01  11300.0
<class 'pandas.core.indexes.datetimes.DatetimeIndex'>
None

In [6]:
flow_series = testdf["cfs"]
type(flow_series)
# pandas.Series

pandas.core.series.Series

In [7]:
bundle = TimeSeriesBundle(testdf)

In [8]:
print(type(bundle.data.index))      # should be pandas.DatetimeIndex
print(bundle.data.head())
print(bundle.meta["frequency"])

<class 'pandas.core.indexes.datetimes.DatetimeIndex'>
                cfs
time
1940-01-01  24300.0
1940-02-01  57500.0
1940-03-01  69600.0
1940-04-01  29800.0
1940-05-01  11300.0
MS

In [9]:
series1 = load_timeseries_csv('~/signal-extraction/vae_input_data/psl_nino34_index_clean.csv','DATE','INDEX','MS')
series1

            INDEX
DATE
1870-01-01  -1.00
1870-02-01  -1.20
1870-03-01  -0.83
1870-04-01  -0.81
1870-05-01  -1.27
...           ...
2025-01-01  -0.76
2025-02-01  -0.39
2025-03-01   0.05
2025-04-01  -0.08
2025-05-01  -0.08

[1865 rows x 1 columns]

In [10]:
nino = series1['INDEX']
type(nino)

pandas.core.series.Series

In [11]:
bundle.add_series('INDEX',nino, align = True)

In [12]:
bundle.refresh_metadata()

In [13]:
print(bundle.data.columns)

Index(['cfs', 'INDEX'], dtype='object')

In [14]:
print(bundle.meta["columns"]['INDEX'])

{'first_valid': Timestamp('1940-01-01 00:00:00'), 'last_valid': Timestamp('2025-05-01 00:00:00'), 'n_valid': np.int64(1025), 'n_missing': np.int64(1)}

In [15]:
print(bundle)

TimeSeriesBundle(data=                cfs  INDEX
time
1940-01-01  24300.0   1.18
1940-02-01  57500.0   1.38
1940-03-01  69600.0   1.19
1940-04-01  29800.0   0.80
1940-05-01  11300.0   0.34
...             ...    ...
2025-02-01   7730.0  -0.39
2025-03-01   6400.0   0.05
2025-04-01   7480.0  -0.08
2025-05-01   4090.0  -0.08
2025-06-01   2500.0    NaN

[1026 rows x 2 columns], meta={'frequency': 'MS', 'index_start': Timestamp('1940-01-01 00:00:00'), 'index_end': Timestamp('2025-06-01 00:00:00'), 'n_rows': 1026, 'n_columns': 2, 'columns': {'cfs': {'first_valid': Timestamp('1940-01-01 00:00:00'), 'last_valid': Timestamp('2025-06-01 00:00:00'), 'n_valid': np.int64(1026), 'n_missing': np.int64(0)}, 'INDEX': {'first_valid': Timestamp('1940-01-01 00:00:00'), 'last_valid': Timestamp('2025-05-01 00:00:00'), 'n_valid': np.int64(1025), 'n_missing': np.int64(1)}}})

In [16]:
bundle2 = TimeSeriesBundle(nino)

IndexError: tuple index out of range

In [18]:
import pycwt

ModuleNotFoundError: No module named 'pycwt'

In [19]:
%pip install pycwt

Collecting pycwt
  Downloading pycwt-0.5.0b0-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: matplotlib<4,>=3.7 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from pycwt) (3.10.7)
Requirement already satisfied: numpy<3,>=2.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from pycwt) (2.3.4)
Requirement already satisfied: scipy<2,>=1.10 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from pycwt) (1.16.3)
Requirement already satisfied: tqdm<5,>=4.65 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from pycwt) (4.67.1)
Requirement already satisfied: contourpy>=1.0.1 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from matplotlib<4,>=3.7->pycwt) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from matplotlib<4,>=3.7->pycwt) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from matplotlib<4,>=3.7->pycwt) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from matplotlib<4,>=3.7->pycwt) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from matplotlib<4,>=3.7->pycwt) (25.0)
Requirement already satisfied: pillow>=8 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from matplotlib<4,>=3.7->pycwt) (12.0.0)
Requirement already satisfied: pyparsing>=3 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from matplotlib<4,>=3.7->pycwt) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from matplotlib<4,>=3.7->pycwt) (2.9.0)
Requirement already satisfied: six>=1.5 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib<4,>=3.7->pycwt) (1.17.0)
Downloading pycwt-0.5.0b0-py3-none-any.whl (755 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 755.0/755.0 kB 7.1 MB/s  0:00:00
Installing collected packages: pycwt
Successfully installed pycwt-0.5.0b0
Note: you may need to restart the kernel to use updated packages.

In [24]:
import pycwt as wlt
import pandas as pd
import numpy as np

In [5]:
dc = pd.read_csv("~/signal-extraction/vae_input_data/AR_cfs.csv")
dc['time'] = pd.to_datetime(dc['time'])

dc = dc.set_index('time')
dc

                cfs
time
1940-01-31  24300.0
1940-02-29  57500.0
1940-03-31  69600.0
1940-04-30  29800.0
1940-05-31  11300.0
...             ...
2025-02-28   7730.0
2025-03-31   6400.0
2025-04-30   7480.0
2025-05-31   4090.0
2025-06-30   2500.0

[1026 rows x 1 columns]

In [8]:
print(pycwt.__version__)

0.4.0b1.dev10+g3343016af.d20251028

In [11]:
import tqdm

In [13]:
dir(pycwt)

['DOG',
 'MexicanHat',
 'Morlet',
 'Paul',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_version_',
 'absolute_import',
 'ar1',
 'ar1_spectrum',
 'chi2',
 'cwt',
 'division',
 'fft',
 'fft_kwargs',
 'find',
 'get_cache_dir',
 'helpers',
 'icwt',
 'mothers',
 'numpy',
 'print_function',
 'rednoise',
 'significance',
 'tqdm',
 'unicode_literals',
 'version',
 'wavelet',
 'wct',
 'wct_significance',
 'xwt']

In [22]:
help(pycwt.wavelet)

Help on module pycwt.wavelet in pycwt:

NAME
    pycwt.wavelet - PyCWT core wavelet transform functions.

FUNCTIONS
    cwt(signal, dt, dj=0.08333333333333333, s0=-1, J=-1, wavelet='morlet', freqs=None)
        Continuous wavelet transform of the signal at specified scales.

        Parameters
        ----------
        signal : numpy.ndarray, list
            Input signal array.
        dt : float
            Sampling interval.
        dj : float, optional
            Spacing between discrete scales. Default value is 1/12.
            Smaller values will result in better scale resolution, but
            slower calculation and plot.
        s0 : float, optional
            Smallest scale of the wavelet. Default value is 2*dt.
        J : float, optional
            Number of scales less one. Scales range from s0 up to
            s0 * 2**(J * dj), which gives a total of (J + 1) scales.
            Default is J = (log2(N * dt / s0)) / dj.
        wavelet : instance of Wavelet class, or string
            Mother wavelet class. Default is Morlet wavelet.
        freqs : numpy.ndarray, optional
            Custom frequencies to use instead of the ones corresponding
            to the scales described above. Corresponding scales are
            calculated using the wavelet Fourier wavelength.

        Returns
        -------
        W : numpy.ndarray
            Wavelet transform according to the selected mother wavelet.
            Has (J+1) x N dimensions.
        sj : numpy.ndarray
            Vector of scale indices given by sj = s0 * 2**(j * dj),
            j={0, 1, ..., J}.
        freqs : array like
            Vector of Fourier frequencies (in 1 / time units) that
            corresponds to the wavelet scales.
        coi : numpy.ndarray
            Returns the cone of influence, which is a vector of N
            points containing the maximum Fourier period of useful
            information at that particular time. Periods greater than
            those are subject to edge effects.
        fft : numpy.ndarray
            Normalized fast Fourier transform of the input signal.
        fftfreqs : numpy.ndarray
            Fourier frequencies (in 1/time units) for the calculated
            FFT spectrum.

        Example
        -------
        >> mother = wavelet.Morlet(6.)
        >> wave, scales, freqs, coi, fft, fftfreqs = wavelet.cwt(signal,
               0.25, 0.25, 0.5, 28, mother)

    icwt(W, sj, dt, dj=0.08333333333333333, wavelet='morlet')
        Inverse continuous wavelet transform.

        Parameters
        ----------
        W : numpy.ndarray
            Wavelet transform, the result of the `cwt` function.
        sj : numpy.ndarray
            Vector of scale indices as returned by the `cwt` function.
        dt : float
            Sample spacing.
        dj : float, optional
            Spacing between discrete scales as used in the `cwt`
            function. Default value is 0.25.
        wavelet : instance of Wavelet class, or string
            Mother wavelet class. Default is Morlet

        Returns
        -------
        iW : numpy.ndarray
            Inverse wavelet transform.

        Example
        -------
        >> mother = wavelet.Morlet()
        >> wave, scales, freqs, coi, fft, fftfreqs = wavelet.cwt(var,
               0.25, 0.25, 0.5, 28, mother)
        >> iwave = wavelet.icwt(wave, scales, 0.25, 0.25, mother)

    significance(signal, dt, scales, sigma_test=0, alpha=None, significance_level=0.95, dof=-1, wavelet='morlet')
        Significance test for the one dimensional wavelet transform.

        Parameters
        ----------
        signal : array like, float
            Input signal array. If a float number is given, then the
            variance is assumed to have this value. If an array is
            given, then its variance is automatically computed.
        dt : float
            Sample spacing.
        scales : array like
            Vector of scale indices given returned by `cwt` function.
        sigma_test : int, optional
            Sets the type of significance test to be performed.
            Accepted values are 0 (default), 1 or 2. See notes below for
            further details.
        alpha : float, optional
            Lag-1 autocorrelation, used for the significance levels.
            Default is 0.0.
        significance_level : float, optional
            Significance level to use. Default is 0.95.
        dof : variant, optional
            Degrees of freedom for significance test to be set
            according to the type set in sigma_test.
        wavelet : instance of Wavelet class, or string
            Mother wavelet class. Default is Morlet

        Returns
        -------
        signif : array like
            Significance levels as a function of scale.
        fft_theor (array like):
            Theoretical red-noise spectrum as a function of period.

        Notes
        -----
        If sigma_test is set to 0, performs a regular chi-square test,
        according to Torrence and Compo (1998) equation 18.

        If set to 1, performs a time-average test (equation 23). In
        this case, dof should be set to the number of local wavelet
        spectra that where averaged together. For the global
        wavelet spectra it would be dof=N, the number of points in
        the time-series.

        If set to 2, performs a scale-average test (equations 25 to
        28). In this case dof should be set to a two element vector
        [s1, s2], which gives the scale range that were averaged
        together. If, for example, the average between scales 2 and
        8 was taken, then dof=[2, 8].

    wct(y1, y2, dt, dj=0.08333333333333333, s0=-1, J=-1, sig=True, significance_level=0.95, wavelet='morlet', normalize=True, **kwargs)
        Wavelet coherence transform (WCT).

        The WCT finds regions in time frequency space where the two time
        series co-vary, but do not necessarily have high power.

        Parameters
        ----------
        y1, y2 : numpy.ndarray, list
            Input signals.
        dt : float
            Sample spacing.
        dj : float, optional
            Spacing between discrete scales. Default value is 1/12.
            Smaller values will result in better scale resolution, but
            slower calculation and plot.
        s0 : float, optional
            Smallest scale of the wavelet. Default value is 2*dt.
        J : float, optional
            Number of scales less one. Scales range from s0 up to
            s0 * 2**(J * dj), which gives a total of (J + 1) scales.
            Default is J = (log2(N*dt/so))/dj.
        sig : bool
            set to compute signficance, default is True
        significance_level (float, optional) :
            Significance level to use. Default is 0.95.
        normalize (boolean, optional) :
            If set to true, normalizes CWT by the standard deviation of
            the signals.

        Returns
        -------
        WCT : magnitude of coherence
        aWCT : phase angle of coherence
        coi (array like):
            Cone of influence, which is a vector of N points containing
            the maximum Fourier period of useful information at that
            particular time. Periods greater than those are subject to
            edge effects.
        freq (array like):
            Vector of Fourier equivalent frequencies (in 1 / time units)    coi :
        sig :  Significance levels as a function of scale
           if sig=True when called, otherwise zero.

        See also
        --------
        cwt, xwt

    wct_significance(al1, al2, dt, dj, s0, J, significance_level=0.95, wavelet='morlet', mc_count=300, progress=True, cache=True)
        Wavelet coherence transform significance.

        Calculates WCT significance using Monte Carlo simulations with
        95% confidence.

        Parameters
        ----------
        al1, al2: float
            Lag-1 autoregressive coeficients of both time series.
        dt : float
            Sample spacing.
        dj : float, optional
            Spacing between discrete scales. Default value is 1/12.
            Smaller values will result in better scale resolution, but
            slower calculation and plot.
        s0 : float, optional
            Smallest scale of the wavelet. Default value is 2*dt.
        J : float, optional
            Number of scales less one. Scales range from s0 up to
            s0 * 2**(J * dj), which gives a total of (J + 1) scales.
            Default is J = (log2(N*dt/so))/dj.
        significance_level : float, optional
            Significance level to use. Default is 0.95.
        wavelet : instance of a wavelet class, optional
            Mother wavelet class. Default is Morlet wavelet.
        mc_count : integer, optional
            Number of Monte Carlo simulations. Default is 300.
        progress : bool, optional
            If `True` (default), shows progress bar on screen.
        cache : bool, optional
            If `True` (default) saves cache to file.

        Returns
        -------
        TODO

    xwt(y1, y2, dt, dj=0.08333333333333333, s0=-1, J=-1, significance_level=0.95, wavelet='morlet', normalize=True)
        Cross wavelet transform (XWT) of two signals.

        The XWT finds regions in time frequency space where the time series
        show high common power.

        Parameters
        ----------
        y1, y2 : numpy.ndarray, list
            Input signal array to calculate cross wavelet transform.
        dt : float
            Sample spacing.
        dj : float, optional
            Spacing between discrete scales. Default value is 1/12.
            Smaller values will result in better scale resolution, but
            slower calculation and plot.
        s0 : float, optional
            Smallest scale of the wavelet. Default value is 2*dt.
        J : float, optional
            Number of scales less one. Scales range from s0 up to
            s0 * 2**(J * dj), which gives a total of (J + 1) scales.
            Default is J = (log2(N*dt/so))/dj.
        wavelet : instance of a wavelet class, optional
            Mother wavelet class. Default is Morlet wavelet.
        significance_level : float, optional
            Significance level to use. Default is 0.95.
        normalize : bool, optional
            If set to true, normalizes CWT by the standard deviation of
            the signals.

        Returns
        -------
        xwt (array like):
            Cross wavelet transform according to the selected mother
            wavelet.
        x (array like):
            Intersected independent variable.
        coi (array like):
            Cone of influence, which is a vector of N points containing
            the maximum Fourier period of useful information at that
            particular time. Periods greater than those are subject to
            edge effects.
        freqs (array like):
            Vector of Fourier equivalent frequencies (in 1 / time units)
            that correspond to the wavelet scales.
        signif (array like):
            Significance levels as a function of scale.

        Notes
        -----
        Torrence and Compo (1998) state that the percent point function
        (PPF) -- inverse of the cumulative distribution function -- of a
        chi-square distribution at 95% confidence and two degrees of
        freedom is Z2(95%)=3.999. However, calculating the PPF using
        chi2.ppf gives Z2(95%)=5.991. To ensure similar significance
        intervals as in Grinsted et al. (2004), one has to use confidence
        of 86.46%.

DATA
    chi2 = <scipy.stats._continuous_distns.chi2_gen object>
        A chi-squared continuous random variable.

        For the noncentral chi-square distribution, see `ncx2`.

        As an instance of the `rv_continuous` class, `chi2` object inherits from it
        a collection of generic methods (see below for the full list),
        and completes them with details specific for this particular distribution.

        Methods
        -------
        rvs(df, loc=0, scale=1, size=1, random_state=None)
            Random variates.
        pdf(x, df, loc=0, scale=1)
            Probability density function.
        logpdf(x, df, loc=0, scale=1)
            Log of the probability density function.
        cdf(x, df, loc=0, scale=1)
            Cumulative distribution function.
        logcdf(x, df, loc=0, scale=1)
            Log of the cumulative distribution function.
        sf(x, df, loc=0, scale=1)
            Survival function  (also defined as ``1 - cdf``, but `sf` is sometimes more accurate).
        logsf(x, df, loc=0, scale=1)
            Log of the survival function.
        ppf(q, df, loc=0, scale=1)
            Percent point function (inverse of ``cdf`` --- percentiles).
        isf(q, df, loc=0, scale=1)
            Inverse survival function (inverse of ``sf``).
        moment(order, df, loc=0, scale=1)
            Non-central moment of the specified order.
        stats(df, loc=0, scale=1, moments='mv')
            Mean('m'), variance('v'), skew('s'), and/or kurtosis('k').
        entropy(df, loc=0, scale=1)
            (Differential) entropy of the RV.
        fit(data)
            Parameter estimates for generic data.
            See `scipy.stats.rv_continuous.fit <https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.rv_continuous.fit.html#scipy.stats.rv_continuous.fit>`__ for detailed documentation of the
            keyword arguments.
        expect(func, args=(df,), loc=0, scale=1, lb=None, ub=None, conditional=False, **kwds)
            Expected value of a function (of one argument) with respect to the distribution.
        median(df, loc=0, scale=1)
            Median of the distribution.
        mean(df, loc=0, scale=1)
            Mean of the distribution.
        var(df, loc=0, scale=1)
            Variance of the distribution.
        std(df, loc=0, scale=1)
            Standard deviation of the distribution.
        interval(confidence, df, loc=0, scale=1)
            Confidence interval with equal areas around the median.

        See Also
        --------
        ncx2

        Notes
        -----
        The probability density function for `chi2` is:

        .. math::

            f(x, k) = \frac{1}{2^{k/2} \Gamma \left( k/2 \right)}
                       x^{k/2-1} \exp \left( -x/2 \right)

        for :math:`x > 0`  and :math:`k > 0` (degrees of freedom, denoted ``df``
        in the implementation).

        `chi2` takes ``df`` as a shape parameter.

        The chi-squared distribution is a special case of the gamma
        distribution, with gamma parameters ``a = df/2``, ``loc = 0`` and
        ``scale = 2``.

        The probability density above is defined in the "standardized" form. To shift
        and/or scale the distribution use the ``loc`` and ``scale`` parameters.
        Specifically, ``chi2.pdf(x, df, loc, scale)`` is identically
        equivalent to ``chi2.pdf(y, df) / scale`` with
        ``y = (x - loc) / scale``. Note that shifting the location of a distribution
        does not make it a "noncentral" distribution; noncentral generalizations of
        some distributions are available in separate classes.

        Examples
        --------
        >>> import numpy as np
        >>> from scipy.stats import chi2
        >>> import matplotlib.pyplot as plt
        >>> fig, ax = plt.subplots(1, 1)

        Get the support:

        >>> df = 55
        >>> lb, ub = chi2.support(df)

        Calculate the first four moments:

        >>> mean, var, skew, kurt = chi2.stats(df, moments='mvsk')

        Display the probability density function (``pdf``):

        >>> x = np.linspace(chi2.ppf(0.01, df),
        ...                 chi2.ppf(0.99, df), 100)
        >>> ax.plot(x, chi2.pdf(x, df),
        ...        'r-', lw=5, alpha=0.6, label='chi2 pdf')

        Alternatively, the distribution object can be called (as a function)
        to fix the shape, location and scale parameters. This returns a "frozen"
        RV object holding the given parameters fixed.

        Freeze the distribution and display the frozen ``pdf``:

        >>> rv = chi2(df)
        >>> ax.plot(x, rv.pdf(x), 'k-', lw=2, label='frozen pdf')

        Check accuracy of ``cdf`` and ``ppf``:

        >>> vals = chi2.ppf([0.001, 0.5, 0.999], df)
        >>> np.allclose([0.001, 0.5, 0.999], chi2.cdf(vals, df))
        True

        Generate random numbers:

        >>> r = chi2.rvs(df, size=1000)

        And compare the histogram:

        >>> ax.hist(r, density=True, bins='auto', histtype='stepfilled', alpha=0.2)
        >>> ax.set_xlim([x[0], x[-1]])
        >>> ax.legend(loc='best', frameon=False)
        >>> plt.show()

FILE
    /srv/conda/envs/notebook/lib/python3.12/site-packages/pycwt/wavelet.py

In [20]:
help(pycwt.cwt)

Help on function cwt in module pycwt.wavelet:

cwt(signal, dt, dj=0.08333333333333333, s0=-1, J=-1, wavelet='morlet', freqs=None)
    Continuous wavelet transform of the signal at specified scales.

    Parameters
    ----------
    signal : numpy.ndarray, list
        Input signal array.
    dt : float
        Sampling interval.
    dj : float, optional
        Spacing between discrete scales. Default value is 1/12.
        Smaller values will result in better scale resolution, but
        slower calculation and plot.
    s0 : float, optional
        Smallest scale of the wavelet. Default value is 2*dt.
    J : float, optional
        Number of scales less one. Scales range from s0 up to
        s0 * 2**(J * dj), which gives a total of (J + 1) scales.
        Default is J = (log2(N * dt / s0)) / dj.
    wavelet : instance of Wavelet class, or string
        Mother wavelet class. Default is Morlet wavelet.
    freqs : numpy.ndarray, optional
        Custom frequencies to use instead of the ones corresponding
        to the scales described above. Corresponding scales are
        calculated using the wavelet Fourier wavelength.

    Returns
    -------
    W : numpy.ndarray
        Wavelet transform according to the selected mother wavelet.
        Has (J+1) x N dimensions.
    sj : numpy.ndarray
        Vector of scale indices given by sj = s0 * 2**(j * dj),
        j={0, 1, ..., J}.
    freqs : array like
        Vector of Fourier frequencies (in 1 / time units) that
        corresponds to the wavelet scales.
    coi : numpy.ndarray
        Returns the cone of influence, which is a vector of N
        points containing the maximum Fourier period of useful
        information at that particular time. Periods greater than
        those are subject to edge effects.
    fft : numpy.ndarray
        Normalized fast Fourier transform of the input signal.
    fftfreqs : numpy.ndarray
        Fourier frequencies (in 1/time units) for the calculated
        FFT spectrum.

    Example
    -------
    >> mother = wavelet.Morlet(6.)
    >> wave, scales, freqs, coi, fft, fftfreqs = wavelet.cwt(signal,
           0.25, 0.25, 0.5, 28, mother)

In [25]:
mother = wlt.Morlet(6.)

In [30]:
print(dc.type)

AttributeError: 'DataFrame' object has no attribute 'type'

In [28]:
wave, scales, freqs, coi, fft, fftfreqs = wlt.cwt(dc['cfs'],
           0.25, 0.25, 0.5, 28, mother)

KeyError: 'ALIGNED'

In [19]:
help(pycwt.wavelet)

Help on module pycwt.wavelet in pycwt:

NAME
    pycwt.wavelet - PyCWT core wavelet transform functions.

FUNCTIONS
    cwt(signal, dt, dj=0.08333333333333333, s0=-1, J=-1, wavelet='morlet', freqs=None)
        Continuous wavelet transform of the signal at specified scales.

        Parameters
        ----------
        signal : numpy.ndarray, list
            Input signal array.
        dt : float
            Sampling interval.
        dj : float, optional
            Spacing between discrete scales. Default value is 1/12.
            Smaller values will result in better scale resolution, but
            slower calculation and plot.
        s0 : float, optional
            Smallest scale of the wavelet. Default value is 2*dt.
        J : float, optional
            Number of scales less one. Scales range from s0 up to
            s0 * 2**(J * dj), which gives a total of (J + 1) scales.
            Default is J = (log2(N * dt / s0)) / dj.
        wavelet : instance of Wavelet class, or string
            Mother wavelet class. Default is Morlet wavelet.
        freqs : numpy.ndarray, optional
            Custom frequencies to use instead of the ones corresponding
            to the scales described above. Corresponding scales are
            calculated using the wavelet Fourier wavelength.

        Returns
        -------
        W : numpy.ndarray
            Wavelet transform according to the selected mother wavelet.
            Has (J+1) x N dimensions.
        sj : numpy.ndarray
            Vector of scale indices given by sj = s0 * 2**(j * dj),
            j={0, 1, ..., J}.
        freqs : array like
            Vector of Fourier frequencies (in 1 / time units) that
            corresponds to the wavelet scales.
        coi : numpy.ndarray
            Returns the cone of influence, which is a vector of N
            points containing the maximum Fourier period of useful
            information at that particular time. Periods greater than
            those are subject to edge effects.
        fft : numpy.ndarray
            Normalized fast Fourier transform of the input signal.
        fftfreqs : numpy.ndarray
            Fourier frequencies (in 1/time units) for the calculated
            FFT spectrum.

        Example
        -------
        >> mother = wavelet.Morlet(6.)
        >> wave, scales, freqs, coi, fft, fftfreqs = wavelet.cwt(signal,
               0.25, 0.25, 0.5, 28, mother)

    icwt(W, sj, dt, dj=0.08333333333333333, wavelet='morlet')
        Inverse continuous wavelet transform.

        Parameters
        ----------
        W : numpy.ndarray
            Wavelet transform, the result of the `cwt` function.
        sj : numpy.ndarray
            Vector of scale indices as returned by the `cwt` function.
        dt : float
            Sample spacing.
        dj : float, optional
            Spacing between discrete scales as used in the `cwt`
            function. Default value is 0.25.
        wavelet : instance of Wavelet class, or string
            Mother wavelet class. Default is Morlet

        Returns
        -------
        iW : numpy.ndarray
            Inverse wavelet transform.

        Example
        -------
        >> mother = wavelet.Morlet()
        >> wave, scales, freqs, coi, fft, fftfreqs = wavelet.cwt(var,
               0.25, 0.25, 0.5, 28, mother)
        >> iwave = wavelet.icwt(wave, scales, 0.25, 0.25, mother)

    significance(signal, dt, scales, sigma_test=0, alpha=None, significance_level=0.95, dof=-1, wavelet='morlet')
        Significance test for the one dimensional wavelet transform.

        Parameters
        ----------
        signal : array like, float
            Input signal array. If a float number is given, then the
            variance is assumed to have this value. If an array is
            given, then its variance is automatically computed.
        dt : float
            Sample spacing.
        scales : array like
            Vector of scale indices given returned by `cwt` function.
        sigma_test : int, optional
            Sets the type of significance test to be performed.
            Accepted values are 0 (default), 1 or 2. See notes below for
            further details.
        alpha : float, optional
            Lag-1 autocorrelation, used for the significance levels.
            Default is 0.0.
        significance_level : float, optional
            Significance level to use. Default is 0.95.
        dof : variant, optional
            Degrees of freedom for significance test to be set
            according to the type set in sigma_test.
        wavelet : instance of Wavelet class, or string
            Mother wavelet class. Default is Morlet

        Returns
        -------
        signif : array like
            Significance levels as a function of scale.
        fft_theor (array like):
            Theoretical red-noise spectrum as a function of period.

        Notes
        -----
        If sigma_test is set to 0, performs a regular chi-square test,
        according to Torrence and Compo (1998) equation 18.

        If set to 1, performs a time-average test (equation 23). In
        this case, dof should be set to the number of local wavelet
        spectra that where averaged together. For the global
        wavelet spectra it would be dof=N, the number of points in
        the time-series.

        If set to 2, performs a scale-average test (equations 25 to
        28). In this case dof should be set to a two element vector
        [s1, s2], which gives the scale range that were averaged
        together. If, for example, the average between scales 2 and
        8 was taken, then dof=[2, 8].

    wct(y1, y2, dt, dj=0.08333333333333333, s0=-1, J=-1, sig=True, significance_level=0.95, wavelet='morlet', normalize=True, **kwargs)
        Wavelet coherence transform (WCT).

        The WCT finds regions in time frequency space where the two time
        series co-vary, but do not necessarily have high power.

        Parameters
        ----------
        y1, y2 : numpy.ndarray, list
            Input signals.
        dt : float
            Sample spacing.
        dj : float, optional
            Spacing between discrete scales. Default value is 1/12.
            Smaller values will result in better scale resolution, but
            slower calculation and plot.
        s0 : float, optional
            Smallest scale of the wavelet. Default value is 2*dt.
        J : float, optional
            Number of scales less one. Scales range from s0 up to
            s0 * 2**(J * dj), which gives a total of (J + 1) scales.
            Default is J = (log2(N*dt/so))/dj.
        sig : bool
            set to compute signficance, default is True
        significance_level (float, optional) :
            Significance level to use. Default is 0.95.
        normalize (boolean, optional) :
            If set to true, normalizes CWT by the standard deviation of
            the signals.

        Returns
        -------
        WCT : magnitude of coherence
        aWCT : phase angle of coherence
        coi (array like):
            Cone of influence, which is a vector of N points containing
            the maximum Fourier period of useful information at that
            particular time. Periods greater than those are subject to
            edge effects.
        freq (array like):
            Vector of Fourier equivalent frequencies (in 1 / time units)    coi :
        sig :  Significance levels as a function of scale
           if sig=True when called, otherwise zero.

        See also
        --------
        cwt, xwt

    wct_significance(al1, al2, dt, dj, s0, J, significance_level=0.95, wavelet='morlet', mc_count=300, progress=True, cache=True)
        Wavelet coherence transform significance.

        Calculates WCT significance using Monte Carlo simulations with
        95% confidence.

        Parameters
        ----------
        al1, al2: float
            Lag-1 autoregressive coeficients of both time series.
        dt : float
            Sample spacing.
        dj : float, optional
            Spacing between discrete scales. Default value is 1/12.
            Smaller values will result in better scale resolution, but
            slower calculation and plot.
        s0 : float, optional
            Smallest scale of the wavelet. Default value is 2*dt.
        J : float, optional
            Number of scales less one. Scales range from s0 up to
            s0 * 2**(J * dj), which gives a total of (J + 1) scales.
            Default is J = (log2(N*dt/so))/dj.
        significance_level : float, optional
            Significance level to use. Default is 0.95.
        wavelet : instance of a wavelet class, optional
            Mother wavelet class. Default is Morlet wavelet.
        mc_count : integer, optional
            Number of Monte Carlo simulations. Default is 300.
        progress : bool, optional
            If `True` (default), shows progress bar on screen.
        cache : bool, optional
            If `True` (default) saves cache to file.

        Returns
        -------
        TODO

    xwt(y1, y2, dt, dj=0.08333333333333333, s0=-1, J=-1, significance_level=0.95, wavelet='morlet', normalize=True)
        Cross wavelet transform (XWT) of two signals.

        The XWT finds regions in time frequency space where the time series
        show high common power.

        Parameters
        ----------
        y1, y2 : numpy.ndarray, list
            Input signal array to calculate cross wavelet transform.
        dt : float
            Sample spacing.
        dj : float, optional
            Spacing between discrete scales. Default value is 1/12.
            Smaller values will result in better scale resolution, but
            slower calculation and plot.
        s0 : float, optional
            Smallest scale of the wavelet. Default value is 2*dt.
        J : float, optional
            Number of scales less one. Scales range from s0 up to
            s0 * 2**(J * dj), which gives a total of (J + 1) scales.
            Default is J = (log2(N*dt/so))/dj.
        wavelet : instance of a wavelet class, optional
            Mother wavelet class. Default is Morlet wavelet.
        significance_level : float, optional
            Significance level to use. Default is 0.95.
        normalize : bool, optional
            If set to true, normalizes CWT by the standard deviation of
            the signals.

        Returns
        -------
        xwt (array like):
            Cross wavelet transform according to the selected mother
            wavelet.
        x (array like):
            Intersected independent variable.
        coi (array like):
            Cone of influence, which is a vector of N points containing
            the maximum Fourier period of useful information at that
            particular time. Periods greater than those are subject to
            edge effects.
        freqs (array like):
            Vector of Fourier equivalent frequencies (in 1 / time units)
            that correspond to the wavelet scales.
        signif (array like):
            Significance levels as a function of scale.

        Notes
        -----
        Torrence and Compo (1998) state that the percent point function
        (PPF) -- inverse of the cumulative distribution function -- of a
        chi-square distribution at 95% confidence and two degrees of
        freedom is Z2(95%)=3.999. However, calculating the PPF using
        chi2.ppf gives Z2(95%)=5.991. To ensure similar significance
        intervals as in Grinsted et al. (2004), one has to use confidence
        of 86.46%.

DATA
    chi2 = <scipy.stats._continuous_distns.chi2_gen object>
        A chi-squared continuous random variable.

        For the noncentral chi-square distribution, see `ncx2`.

        As an instance of the `rv_continuous` class, `chi2` object inherits from it
        a collection of generic methods (see below for the full list),
        and completes them with details specific for this particular distribution.

        Methods
        -------
        rvs(df, loc=0, scale=1, size=1, random_state=None)
            Random variates.
        pdf(x, df, loc=0, scale=1)
            Probability density function.
        logpdf(x, df, loc=0, scale=1)
            Log of the probability density function.
        cdf(x, df, loc=0, scale=1)
            Cumulative distribution function.
        logcdf(x, df, loc=0, scale=1)
            Log of the cumulative distribution function.
        sf(x, df, loc=0, scale=1)
            Survival function  (also defined as ``1 - cdf``, but `sf` is sometimes more accurate).
        logsf(x, df, loc=0, scale=1)
            Log of the survival function.
        ppf(q, df, loc=0, scale=1)
            Percent point function (inverse of ``cdf`` --- percentiles).
        isf(q, df, loc=0, scale=1)
            Inverse survival function (inverse of ``sf``).
        moment(order, df, loc=0, scale=1)
            Non-central moment of the specified order.
        stats(df, loc=0, scale=1, moments='mv')
            Mean('m'), variance('v'), skew('s'), and/or kurtosis('k').
        entropy(df, loc=0, scale=1)
            (Differential) entropy of the RV.
        fit(data)
            Parameter estimates for generic data.
            See `scipy.stats.rv_continuous.fit <https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.rv_continuous.fit.html#scipy.stats.rv_continuous.fit>`__ for detailed documentation of the
            keyword arguments.
        expect(func, args=(df,), loc=0, scale=1, lb=None, ub=None, conditional=False, **kwds)
            Expected value of a function (of one argument) with respect to the distribution.
        median(df, loc=0, scale=1)
            Median of the distribution.
        mean(df, loc=0, scale=1)
            Mean of the distribution.
        var(df, loc=0, scale=1)
            Variance of the distribution.
        std(df, loc=0, scale=1)
            Standard deviation of the distribution.
        interval(confidence, df, loc=0, scale=1)
            Confidence interval with equal areas around the median.

        See Also
        --------
        ncx2

        Notes
        -----
        The probability density function for `chi2` is:

        .. math::

            f(x, k) = \frac{1}{2^{k/2} \Gamma \left( k/2 \right)}
                       x^{k/2-1} \exp \left( -x/2 \right)

        for :math:`x > 0`  and :math:`k > 0` (degrees of freedom, denoted ``df``
        in the implementation).

        `chi2` takes ``df`` as a shape parameter.

        The chi-squared distribution is a special case of the gamma
        distribution, with gamma parameters ``a = df/2``, ``loc = 0`` and
        ``scale = 2``.

        The probability density above is defined in the "standardized" form. To shift
        and/or scale the distribution use the ``loc`` and ``scale`` parameters.
        Specifically, ``chi2.pdf(x, df, loc, scale)`` is identically
        equivalent to ``chi2.pdf(y, df) / scale`` with
        ``y = (x - loc) / scale``. Note that shifting the location of a distribution
        does not make it a "noncentral" distribution; noncentral generalizations of
        some distributions are available in separate classes.

        Examples
        --------
        >>> import numpy as np
        >>> from scipy.stats import chi2
        >>> import matplotlib.pyplot as plt
        >>> fig, ax = plt.subplots(1, 1)

        Get the support:

        >>> df = 55
        >>> lb, ub = chi2.support(df)

        Calculate the first four moments:

        >>> mean, var, skew, kurt = chi2.stats(df, moments='mvsk')

        Display the probability density function (``pdf``):

        >>> x = np.linspace(chi2.ppf(0.01, df),
        ...                 chi2.ppf(0.99, df), 100)
        >>> ax.plot(x, chi2.pdf(x, df),
        ...        'r-', lw=5, alpha=0.6, label='chi2 pdf')

        Alternatively, the distribution object can be called (as a function)
        to fix the shape, location and scale parameters. This returns a "frozen"
        RV object holding the given parameters fixed.

        Freeze the distribution and display the frozen ``pdf``:

        >>> rv = chi2(df)
        >>> ax.plot(x, rv.pdf(x), 'k-', lw=2, label='frozen pdf')

        Check accuracy of ``cdf`` and ``ppf``:

        >>> vals = chi2.ppf([0.001, 0.5, 0.999], df)
        >>> np.allclose([0.001, 0.5, 0.999], chi2.cdf(vals, df))
        True

        Generate random numbers:

        >>> r = chi2.rvs(df, size=1000)

        And compare the histogram:

        >>> ax.hist(r, density=True, bins='auto', histtype='stepfilled', alpha=0.2)
        >>> ax.set_xlim([x[0], x[-1]])
        >>> ax.legend(loc='best', frameon=False)
        >>> plt.show()

FILE
    /srv/conda/envs/notebook/lib/python3.12/site-packages/pycwt/wavelet.py

In [7]:
nino3 = pycwt.load_dataset("dc")  # Load sample time-series.

AttributeError: module 'PyCWT' has no attribute 'load_dataset'

In [10]:
wavelet = pycwt.Morlet(6)             # Instantiate mother wavelet.
result = wavelet.run(dc)              # Run wavelet analysis.
result.plot()

AttributeError: 'Morlet' object has no attribute 'run'